var routeApp = angular.module('routeApp',['ngRoute']);
routeApp.config(['$routeProvider',function($routeProvider){
	$routeProvider
	.when('/column',{
		templateUrl:'column.html'
	})
	.when('/table',{
		templateUrl:'table.html',
		controller:'RouteListCtl'
	})
	.when('/button',{
		templateUrl:'button.html',
		controller:'RouteListCtl'
	})
	.when('/dropdown',{
		templateUrl:'dropdown.html',
		controller:'RouteDropdownCtl'
	})
	.when('/form',{
		templateUrl:'form.html'
	})
	.when('/font',{
		templateUrl:'font.html',
		controller:'RouteFontCtrl'
	})
	.when('/label',{
		templateUrl:'label.html'
	})
	.otherwise({
		redirectTo:'/'
	});
}]);